### ISSUE TITLE
Failure to process markdown on non-index pages, failure to process page config on non-root pages

### ISSUE THREAD

**Issue by zbee** [pancakeio/detect#3]
Essentially, sites that functioned a year ago on the service no longer work after subscribing.

Regardless of file extension (.txt, .md, .markdown, or no extension at all), using the pancake.io service after the service was finally resurrected (after it was down on-and-off for months) fails to actually process any markdown on [my website](http://imzbee.pancakeapps.com/post/online_safety.markdown).

Build log is essentially useless:

```
Files:
/projects.txt [3334]
/index.txt [734]
/keybase.txt [3245]
/post/ditto_learning.txt [2652]
/post/online_safety.markdown [7583]

--
Uploaded 60636 bytes from "/"
```
This looks essentially the same for any type of file-extension, there is never any text anything to the effect of "markdown processed successfully".

---

**Possible solution 1:** Adding an additional horizontal ruling after the page config (non-functional)

As seen on [imzbee/index.txt](http://imzbee.pancakeapps.com/index.txt) there is an additional `---` and I thought that maybe that's why [imzbee/](http://imzbee.pancakeapps.com/) works at all (since the page is cut in half - above the additional horizontal ruling), however this changes nothing on non-index pages.

**Possible solution 2:** making all pages indexes in their own folder (somewhat functional)

If you make a page be /whatever/index.txt instead of /whatever.txt (a year ago this was supported), the markdown of the page works, however the page config is still ignored completely and rendered as straight text. So this sort of fixes the problem, but is not in the documentation whatsoever.

---

_Additionally_, there is no listed way to contact you or any other possible pancake.io developers whatsoever. The help documents are adequate (at best), however, for something like this I should not have to really make a GitHub issue, but instead should be able to send a support email, or something similar - I mean, I'm now paying for it, I should get _some_ amount of support.
(Oh, and you can't cancel subscriptions, so if someone decides they're done with you they may perform a charge-back instead, costing you money)

**I know this is the wrong repository for this. I could not identify a correct one, and this was the most recently edited.**

**Comment by octavore** [comment]
Hi @Zbee, I'm sorry you've had a frustrating time. You can always reach out at support@pancake.io, and the subscriptions cancellation button will be up this week. 

For the first issue you've reported, I've identified and fixed a bug with our markdown rendering that caused the header block to be too greedily matched (up to the final `---` instead of the one that closed the header block).

The bug relating to your second issue has also now been fixed. The path `/whatever` is now resolvable with the HTML output from `/whatever.txt` and `/whatever/index.txt`.

I've regenerated your site with the fixes applied, please take a look and let me know if's working correctly for you. Thanks!

**Comment by zbee** [comment]
@octavore Wow! Thanks so much for this wonderful response!

I never saw that email, and I'll be glad to see the unsubscribe button, but will certainly not be using it.

Everything seems to be fixed and functional now, with the following exceptions:

- HTML in the page config `header` item, which used to render, now [doesn't](http://zbee.me/projects).
- My [Keybase Proof](https://imzbee.pancakeapps.com/keybase.txt) is [processed as markdown](http://logs.build.pancake.io/51818/cairo-drive-6875/dropbox_270621391.log), but ignored a `blank: true` page config, and is not actually being rendered as markdown ([image](https://puu.sh/zi67C.png)).
- Unrelated: Reloading any [log-in required page](https://pancake.io/projects/imzbee) works just fine and remembers you're logged in. But if you go to pancake.io and then click `login`, the log-in page does not remember you are already logged in. Also, if you go to the log-in page, and then navigate backwards (with the back button in your browser) the pancake.io site instead has a `dashboard` button where the `login` and `sign up` buttons previously were - I have only made that button show up by going back to the page, it never shows the `dashboard` button when you first go to pancake.io.
- Unrelated: Build time does not actually count / build identifier is not-unique ([page](https://pancake.io/projects/imzbee/builds), [image](https://puu.sh/zi5RP.png))

---

Additionally, is the code you edited on GitHub anywhere? I don't see a recent commit from you indicating where it may have been. I'd love to contribute / make these fixes myself in the future if possible.

**Comment by octavore** [comment]
Thanks again for the feedback! Unfortunately the code for Pancake is not public, but I appreciate the sentiment :) 

With regards to the issues you've raised:

- Fixed bug so HTML in `header` now renders correctly.
- Fixed the bug with `blank: true` to disable CSS in the autogenerated html page – does this show what you expect?
- Will fix this soon
- Build identifier is now a unique random string

**Comment by zbee** [comment]
Fair enough - should the support email then be the go-to for reporting issues such as this?

- Perfect!
- Not quite. The expected behavior is for the page to be processed as markdown, see the `blank: true` config, stop processing markdown so as to display plain text, and also remove the page config options from the displayed plain text. However, it does not remove the page config from the plain text. See [my keybase proof as-is](imzbee.pancakeapps.com/keybase.txt): it is rendered as plain text as it should be, however the page config is still there.
- Also fair.
- Sweet - hopefully users will be able to contact support and provide that string as a reference.

**Comment by Zbee** [comment]
Fair enough - should the support email then be the go-to for reporting issues such as this?

- Perfect!
- Not quite. The expected behavior is for the page to be processed as markdown, see the `blank: true` config, stop processing markdown so as to display plain text, and also remove the page config options from the displayed plain text. However, it does not remove the page config from the plain text. See [my keybase proof as-is](imzbee.pancakeapps.com/keybase.txt): it is rendered as plain text as it should be, however the page config is still there.
- Also fair.
- Sweet - hopefully users will be able to contact support and provide that string as a reference.

**Comment by octavore** [comment]
Yep, send any questions or feedback or bug reports to the support email, and it'll be taken care of! In fact, I'll close out this issue since it looks like its been mostly addressed, and we can continue over email if you'd like.

To wrap up a few threads: I've added the unsubscribe button, and fixed the login/signup page to correctly redirect to the dashboard now. For the `blank: true` behavior, I think for now you should just omit the header and have the txt file reflect the content you want. Unfortunately it'll still cause `.html` files to be generated, but if you reference the file with the original `.txt` extension, that should be as you desired. I'll look into adding some way of maybe disabling Markdown rendering on a per file basis, or maybe an option to only process `.md` files as Markdown.

**Comment by zbee** [comment]
I attempted to reach out to the support email you provided, but have received no response, current issues appear to relate to these. Please review.
